### ISSUE TITLE
Fluid container type does not cascade down to regions

### ISSUE THREAD

**Issue by rszrama** [backdrop-contrib/bootstrap_lite#11] opened 2016-09-09 15:09 UTC
When I change the container type from fixed to fluid, it doesn't appear to cascade down to the regions properly. Even though the theme sets the container-fluid class properly on the page level and region level container divs, it also includes the container class. This results in the width being limited at the region level, even though it isn't at the page level.

**Comment by Gormartsen** [comment] 2016-09-09 15:19
Bootstrap lite doesnot work properly with latest flex box layouts. 

There is a need to fix that.

You can try radix layouts for now.

Regards,
Gor Martsen
@gormartsen

**Comment by bugfolder** [comment] 2021-02-10 14:38
I've run into this, and it looks like the issue is that all of the default layouts include _both_ `container` and `container-fluid` classes, so that the fixed-width breakpoints of the former dominate no matter what.

The function `bootstrap_lite_preprocess_layout()` currently injects the selected container type into the outermost div of the layout. But since the layouts themselves contain `container container-fluid` divs, that ends up double-wrapping content in container divs. I think the outer one is unnecessary.

Since it appears that all of the default layouts include both classes, it should suffice to remove the container type that we don't need. 

So I'd suggest in `bootstrap_lite_preprocess_layout()` that we replace
```
  backdrop_add_js('(function($){ $(".layout").addClass("' . theme_get_setting('bootstrap_lite_container') . '");})(jQuery);', array('type' => 'inline', 'scope' => 'footer'));
```
with
```
  if (theme_get_setting('bootstrap_lite_container') == 'container') {
    backdrop_add_js('(function($){ $(".container.container-fluid").removeClass("container-fluid");})(jQuery);', array('type' => 'inline', 'scope' => 'footer'));
  }
  else {
    backdrop_add_js('(function($){ $(".container.container-fluid").removeClass("container");})(jQuery);', array('type' => 'inline', 'scope' => 'footer'));
  }
```
I've tried this out locally, and it appears to properly support switching between fixed and fluid layouts via the theme settings (with no apparent bad side effects).

I'd appreciate any feedback on the above (e.g., @stpaultim ). If it makes sense to folks, I'll file a PR with the change.

**Comment by bugfolder** [comment] 2021-02-21 14:07
[PR created.](https://github.com/backdrop-contrib/bootstrap_lite/pull/27)

**Comment by stpaultim** [comment] 2021-02-21 21:20
@bugfolder - Thanks for PR. Sorry for not replying earlier. I don't have a lot of time to look at this issue, but you seem to have researched it pretty well. I'm going to go ahead and merge this commit.

**Comment by bugfolder** [comment] 2021-02-24 00:04
Closing this issue; fixed by [PR 27](https://github.com/backdrop-contrib/bootstrap_lite/pull/27).

**Closed as completed by bugfolder** 2021-02-24 00:04 UTC
