### ISSUE TITLE
Logo not showing if Site name is not checked in Configure block "Header block"

### ISSUE THREAD

**Issue by bisonbleu** [backdrop-contrib/bootstrap_lite#6] opened 2015-12-31 21:45 UTC
If only the Logo option is checked in Configure block "Header block", the logo (default backdrop in my case) is not showing. This issue disappears if I use Bartik.

**Comment by Gormartsen** [comment] 2016-01-01 00:19
Thanks . Will check it out.

**Comment by yorkshire-pudding** [comment] 2021-02-05 20:38
@Gormartsen @bisonbleu 

This needs a very small change to the templates/header.tpl.php file:

From line 32 - 39:
`      <?php if (!empty($site_name)): ?>
        <a class="name navbar-brand" href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>">
          <?php if ($logo): ?>
            <img src="<?php print $logo; ?>" alt="<?php print t('Home'); ?>" />
          <?php endif; ?>
          <?php print $site_name; ?>
        </a>
      <?php endif; ?>`

To:

`      <?php if ($site_name || $logo): ?>
        <a class="name navbar-brand" href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>">
          <?php if ($logo): ?>
            <img src="<?php print $logo; ?>" alt="<?php print t('Home'); ?>" />
          <?php endif; ?>
          <?php if ($site_name): ?>
            <?php print $site_name; ?>
          <?php endif; ?>
        </a>
      <?php endif; ?>`

[header.tpl.php.gz](https://github.com/backdrop-contrib/bootstrap_lite/files/5935183/header.tpl.php.gz)

I did try to do a pull request but it won't let me.

**Comment by stpaultim** [comment] 2021-02-05 21:49
@yorkshire-pudding - Did you fork the repo and try to create a PR from your forked copy?

**Comment by stpaultim** [comment] 2021-02-06 02:57
First step. I was able to recreate this problem. Next, I'll test the PR provided by @yorkshire-pudding

**Comment by stpaultim** [comment] 2021-02-06 03:03
I have confirmed that the [PR provided](https://github.com/backdrop-contrib/bootstrap_lite/pull/21) does  fix this problem. 

I'm inclined to merge this PR once I have proper permissions. 

I wonder if there is a problem because this update might suddenly cause logos to appear on sites where they were not appearing and were not intended to appear, but because of this error they were not appearing for the wrong reason.

**Comment by stpaultim** [comment] 2021-02-06 05:06
Thanks @yorkshire-pudding - I went ahead and merged this PR. I'm going to look through the other issues to see if there is anything else we might be able to fix before cutting a new release.

**Closed as completed** 2021-02-06 05:06 UTC
Labels: Fixed
